 - job:
    name: checkboxBuildJob
    project-type: freestyle
    display-name: checkboxBuildJob
    concurrent: true
    workspace: /home/ubuntu/checkbox.io/server-side/site
    retry-count: 3
    builders:
      - shell: |
            sudo npm install
    publishers:
      - post-tasks:
        - matches:
          - log-text: .
            operator: AND
          escalate-status: false
          run-if-job-successful: false
          script: |
            sudo ansible-playbook -i /home/ubuntu/post_build/checkbox_inventory /home/ubuntu/post_build/checkbox_main.yml
    become: yes
