---
  # - name: Checking the status of the checkboxio build
  #   shell: cat /var/lib/jenkins/jobs/checkboxBuildJob/lastSuccessful/log | grep SUCCESS
  #   register: checkboxlog
  #   become: yes

  # - debug:
  #     var:  checkboxlog.stdout
  #   when: checkboxlog.stdout != ""

  - name: Checking the status of the iTrust build
    shell: cat /var/lib/jenkins/jobs/iTrustBuildJob/lastSuccessful/log | grep SUCCESS
    register: iTrustlog
    become: yes

  - debug:
      var: iTrustlog.stdout
    when: iTrustlog.stdout != ""

  - name: Unzipping the files needed to run iTrust on Jenkins
    unarchive:
      src: ./
      dest: ./
  
  
