  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysqlpass | quote}}' vtype='password'
    become: yes

  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysqlpass | quote}}' vtype='password'
    become: yes

  - name: Install MySQL
    apt:  name={{ item }}
    become: yes
    with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client

  - name: Start the MySQL service
    service:
      name: mysql
      enabled: true
